name: update-friends-posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,6,12,18,21 * * *"
  workflow_dispatch:

env:
  # 通用配置
  SIMPLE_MODE: false
  STORAGE_TYPE: ${{ secrets.STORAGE_TYPE }}
  PROXY: ${{ secrets.PROXY }}
  # 数据库配置 (四选一)
  APPID: ${{ secrets.APPID }}
  APPKEY: ${{ secrets.APPKEY }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_IP: ${{ secrets.MYSQL_IP }}
  MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
  MYSQL_DB: ${{ secrets.MYSQL_DB }}
  GITHUB_NAME: ${{ secrets.GH_NAME }}
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: "**/requirements.txt"

    - name: Install dependencies
      working-directory: ./hexo_circle_of_friends
      run: pip install -r requirements.txt

    - name: Configure environment
      run: |
        echo "BASE_PATH=$(pwd)" >> $GITHUB_ENV
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    # LeanCloud 数据库操作
    - name: Update LeanCloud posts
      if: ${{ env.STORAGE_TYPE == 'leancloud' }}
      env:
        LINK: ${{ secrets.LINK }}
      working-directory: ./hexo_circle_of_friends
      run: python run.py

    # MySQL 数据库操作
    - name: Update MySQL posts
      if: ${{ env.STORAGE_TYPE == 'mysql' }}
      working-directory: ./hexo_circle_of_friends
      run: python run.py

    # SQLite 数据库操作
    - name: Update SQLite posts
      if: ${{ env.STORAGE_TYPE == 'sqlite' || env.SIMPLE_MODE == 'true' }}
      run: python ./hexo_circle_of_friends/run.py

    # MongoDB 数据库操作
    - name: Update MongoDB posts
      if: ${{ env.STORAGE_TYPE == 'mongodb' }}
      working-directory: ./hexo_circle_of_friends
      run: python run.py

    # 数据提交模块
    - name: Commit SQLite changes
      if: ${{ env.STORAGE_TYPE == 'sqlite' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update database files"
        file_pattern: data.db
        commit_user_name: ${{ env.GITHUB_NAME }}
        commit_user_email: ${{ env.GITHUB_EMAIL }}
        skip_checkout: true

    # 极简模式处理
    - name: Transform simple mode
      if: ${{ env.SIMPLE_MODE == 'true' }}
      run: python ./hexo_circle_of_friends/utils/simple_mode_transform_json.py

    - name: Commit JSON changes
      if: ${{ env.SIMPLE_MODE == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update JSON data"
        file_pattern: data.json
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions@noreply.github.com
        skip_checkout: true

    # 工作流保活模块
    - name: Prevent workflow timeout
      uses: marocchino/[email protected]
      with:
        timeout-minutes: 2
        same-step: true
